name: GFSLT-VLP
data:
  train_label_path: ./data/Phonexi-2014T/labels.train
  dev_label_path: ./data/Phonexi-2014T/labels.dev
  test_label_path: ./data/Phonexi-2014T/labels.test
  img_path: /mnt/Data/datasets/SLT/PHOENIX-2014-T/fullFrame-210x260px/
  max_length: 300
training:
  wandb: disabled # online or disabled
  scale_embedding: False
model:
  tokenizer: facebook/mbart-large-50
  transformer: facebook/mbart-large-50
  visual_encoder: google/vit-base-patch16-224-in21k  # Free Vision Transformer model
  sign_proj: True
